/**
 * ISO 3166-1 Country codes with English and German names
 * Ordered alphabetically by English name
 */
export interface Country {
  code: string;
  en: string;
  de: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', en: 'Afghanistan', de: 'Afghanistan' },
  { code: 'AL', en: 'Albania', de: 'Albanien' },
  { code: 'DZ', en: 'Algeria', de: 'Algerien' },
  { code: 'AD', en: 'Andorra', de: 'Andorra' },
  { code: 'AO', en: 'Angola', de: 'Angola' },
  { code: 'AR', en: 'Argentina', de: 'Argentinien' },
  { code: 'AM', en: 'Armenia', de: 'Armenien' },
  { code: 'AU', en: 'Australia', de: 'Australien' },
  { code: 'AT', en: 'Austria', de: 'Österreich' },
  { code: 'AZ', en: 'Azerbaijan', de: 'Aserbaidschan' },
  { code: 'BH', en: 'Bahrain', de: 'Bahrain' },
  { code: 'BD', en: 'Bangladesh', de: 'Bangladesch' },
  { code: 'BY', en: 'Belarus', de: 'Weißrussland' },
  { code: 'BE', en: 'Belgium', de: 'Belgien' },
  { code: 'BZ', en: 'Belize', de: 'Belize' },
  { code: 'BO', en: 'Bolivia', de: 'Bolivien' },
  { code: 'BA', en: 'Bosnia and Herzegovina', de: 'Bosnien und Herzegowina' },
  { code: 'BR', en: 'Brazil', de: 'Brasilien' },
  { code: 'BG', en: 'Bulgaria', de: 'Bulgarien' },
  { code: 'CA', en: 'Canada', de: 'Kanada' },
  { code: 'CL', en: 'Chile', de: 'Chile' },
  { code: 'CN', en: 'China', de: 'China' },
  { code: 'CO', en: 'Colombia', de: 'Kolumbien' },
  { code: 'CR', en: 'Costa Rica', de: 'Costa Rica' },
  { code: 'HR', en: 'Croatia', de: 'Kroatien' },
  { code: 'CY', en: 'Cyprus', de: 'Zypern' },
  { code: 'CZ', en: 'Czech Republic', de: 'Tschechien' },
  { code: 'DK', en: 'Denmark', de: 'Dänemark' },
  { code: 'EC', en: 'Ecuador', de: 'Ecuador' },
  { code: 'EG', en: 'Egypt', de: 'Ägypten' },
  { code: 'EE', en: 'Estonia', de: 'Estland' },
  { code: 'FI', en: 'Finland', de: 'Finnland' },
  { code: 'FR', en: 'France', de: 'Frankreich' },
  { code: 'GE', en: 'Georgia', de: 'Georgien' },
  { code: 'DE', en: 'Germany', de: 'Deutschland' },
  { code: 'GR', en: 'Greece', de: 'Griechenland' },
  { code: 'HK', en: 'Hong Kong', de: 'Hongkong' },
  { code: 'HU', en: 'Hungary', de: 'Ungarn' },
  { code: 'IS', en: 'Iceland', de: 'Island' },
  { code: 'IN', en: 'India', de: 'Indien' },
  { code: 'ID', en: 'Indonesia', de: 'Indonesien' },
  { code: 'IR', en: 'Iran', de: 'Iran' },
  { code: 'IQ', en: 'Iraq', de: 'Irak' },
  { code: 'IE', en: 'Ireland', de: 'Irland' },
  { code: 'IL', en: 'Israel', de: 'Israel' },
  { code: 'IT', en: 'Italy', de: 'Italien' },
  { code: 'JP', en: 'Japan', de: 'Japan' },
  { code: 'JO', en: 'Jordan', de: 'Jordanien' },
  { code: 'KZ', en: 'Kazakhstan', de: 'Kasachstan' },
  { code: 'KW', en: 'Kuwait', de: 'Kuwait' },
  { code: 'LV', en: 'Latvia', de: 'Lettland' },
  { code: 'LB', en: 'Lebanon', de: 'Libanon' },
  { code: 'LI', en: 'Liechtenstein', de: 'Liechtenstein' },
  { code: 'LT', en: 'Lithuania', de: 'Litauen' },
  { code: 'LU', en: 'Luxembourg', de: 'Luxemburg' },
  { code: 'MY', en: 'Malaysia', de: 'Malaysia' },
  { code: 'MT', en: 'Malta', de: 'Malta' },
  { code: 'MX', en: 'Mexico', de: 'Mexiko' },
  { code: 'MD', en: 'Moldova', de: 'Moldawien' },
  { code: 'MC', en: 'Monaco', de: 'Monaco' },
  { code: 'ME', en: 'Montenegro', de: 'Montenegro' },
  { code: 'MA', en: 'Morocco', de: 'Marokko' },
  { code: 'NL', en: 'Netherlands', de: 'Niederlande' },
  { code: 'NZ', en: 'New Zealand', de: 'Neuseeland' },
  { code: 'NO', en: 'Norway', de: 'Norwegen' },
  { code: 'OM', en: 'Oman', de: 'Oman' },
  { code: 'PK', en: 'Pakistan', de: 'Pakistan' },
  { code: 'PA', en: 'Panama', de: 'Panama' },
  { code: 'PY', en: 'Paraguay', de: 'Paraguay' },
  { code: 'PE', en: 'Peru', de: 'Peru' },
  { code: 'PH', en: 'Philippines', de: 'Philippinen' },
  { code: 'PL', en: 'Poland', de: 'Polen' },
  { code: 'PT', en: 'Portugal', de: 'Portugal' },
  { code: 'QA', en: 'Qatar', de: 'Katar' },
  { code: 'RO', en: 'Romania', de: 'Rumänien' },
  { code: 'RU', en: 'Russia', de: 'Russland' },
  { code: 'SA', en: 'Saudi Arabia', de: 'Saudi-Arabien' },
  { code: 'RS', en: 'Serbia', de: 'Serbien' },
  { code: 'SG', en: 'Singapore', de: 'Singapur' },
  { code: 'SK', en: 'Slovakia', de: 'Slowakei' },
  { code: 'SI', en: 'Slovenia', de: 'Slowenien' },
  { code: 'ZA', en: 'South Africa', de: 'Südafrika' },
  { code: 'KR', en: 'South Korea', de: 'Südkorea' },
  { code: 'ES', en: 'Spain', de: 'Spanien' },
  { code: 'SE', en: 'Sweden', de: 'Schweden' },
  { code: 'CH', en: 'Switzerland', de: 'Schweiz' },
  { code: 'TW', en: 'Taiwan', de: 'Taiwan' },
  { code: 'TH', en: 'Thailand', de: 'Thailand' },
  { code: 'TR', en: 'Turkey', de: 'Türkei' },
  { code: 'UA', en: 'Ukraine', de: 'Ukraine' },
  { code: 'AE', en: 'United Arab Emirates', de: 'Vereinigte Arabische Emirate' },
  { code: 'GB', en: 'United Kingdom', de: 'Vereinigtes Königreich' },
  { code: 'US', en: 'United States', de: 'Vereinigte Staaten' },
  { code: 'UY', en: 'Uruguay', de: 'Uruguay' },
  { code: 'VE', en: 'Venezuela', de: 'Venezuela' },
  { code: 'VN', en: 'Vietnam', de: 'Vietnam' },
];

/**
 * Get country name by code and locale
 */
export const getCountryName = (code: string, locale: 'en' | 'de' = 'en'): string => {
  const country = COUNTRIES.find(c => c.code === code);
  return country ? country[locale] : code;
};
